name: TrialsOfAshur Dev Logs
description: >
    The ToA dev logs. Updated as frequently as we post them (so roughly once a week barring some missed weeks)
about: >
    Hello from Cerkyrion! Developers of The Trials Of Ashur, an upcoming MOBA game based on Epic's Paragon

master_repo: false
url: "cerkyrion.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Cerkyrion
  avatar:         "https://avatars2.githubusercontent.com/u/44066684?s=240"
  email:          "noreply@cerkyrion.co.uk"
  discord:        "discord.gg/48VatKV"
  # Social networking links used in footer. Update and remove as you like.
  twitter: TrialsOfAshur
  github: https://github.com/cerkyrion
  stackexchange: 
  linkedin: 

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
